language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=myproject, polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-1"
  app: "swe1app"
  env: "swe1-env"
  bucket_name: "elasticbeanstalk-us-east-1-241091061040"
